version: '2'

networks:
  basic:

services:
  coinmarket:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coinmarket
    image: okexcoin:v1
    ports:
      - "9999:80"
    volumes:
      - ./log:/go/src/okex/log
    networks:
      - basic