weixin:
  wxurl: https://u.ifeige.cn/api/message/send

coin:
  btc: BTC-USD-190927
  eth: ETH-USD-190927
  bch: BCH-USD-190927
  eos: EOS-USD-190927
  ltc: LTC-USD-190927

okex:
  endpoint: https://www.okex.me/
  api_key:
  secret_key:
  enable: 1

ifeige:
  secret:
  app_key:
  template_id: 5uZIvSm5GAdUR1X25HNpjuOp6jSiL88v4opn4a4GLa0
  color: "#173177"
ifeige2:
  secret:
  app_key:
  template_id: 5uZIvSm5GAdUR1X25HNpjuOp6jSiL88v4opn4a4GLa0
  color: "#173177"
message:
  max: 4
  first_send: 1
  version: local
  #请求bc接口次数,5次／rate 单位毫秒
  rate: 520
  sleep: 0
  #五条一发
  send_size: 5
  #total 清零 单位秒
  reset_total_time: 60
  #清零时间内没打到多少条
  reset_less_then: 3

future:
  position:
    # 开启查询
    enable: 0
    # 1查询okex 合约持仓
    okex_huobi: 0

huobi:
  api:
    access_key:
    secret_key:
ding:
  url: cb89a5e749e150f9f7365e928
wechat:
  robot: 0


